---
- name: Setup Dotfiles
  hosts: localhost

  vars:
    vital_dependencies:
      - git
      - stow
      - neovim
      - flatpak
      - network-manager-applet
      - dnf-plugins-core

    additional_dependencies:
      - feh
      - curl
      - wget
      - i3
      - i3status
      - i3lock
      - starship
      - wezterm

  tasks:
    - name: Install vital dependencies
      become: true
      dnf:
        name: "{{ vital_dependencies }}"
        state: present

    - name: Run stow
      become: false
      shell: "stow . --target {{ ansible_env.HOME }} --verbose=2"
      register: result
      changed_when: "'LINK:' in result.stderr"

    - name: Install Starship via COPR
      become: true
      community.general.copr:
        name: atim/starship

    - name: Install WezTerm via COPR
      become: true
      community.general.copr:
        name: wezfurlong/wezterm-nightly

    - name: Install rest dependencies
      become: true
      dnf:
        name: "{{ additional_dependencies }}"
        state: present

    - name: Install Ansible Galaxy Roles General
      become: false
      ansible.builtin.command: ansible-galaxy collection install community.general

    - name: Install Flatpak Packages
      community.general.flatpak:
        name:
          - org.gimp.GIMP
