---
- name: Setup Dotfiles
  hosts: localhost

  tasks:
    - name: Ensure the Arch Linux keyring is up to date
      ansible.builtin.pacman:
        name: archlinux-keyring
        state: latest

    - name: Import Packages
      include_vars:
        dir: ansible/variables
        files_matching: "packages.yaml"
        name: packages

    - name: Install Ansible Galaxy Roles General
      become: false
      ansible.builtin.command: |
        ansible-galaxy collection install community.general

    - name: Install core packages
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ packages.main }}"

    - name: Run stow
      become: false
      shell: "stow . --target {{ ansible_env.HOME }} --verbose=2"
      register: result
      changed_when: "'LINK:' in result.stderr"

    - name: Install system fonts
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ packages.fonts }}"

    - name: Check if yay is installed
      command: yay --version
      register: yay_check
      ignore_errors: true

    - name: Clone yay repository
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /tmp/yay
        clone: true
        update: true
      when: yay_check.failed

    - name: Build and install yay
      command: makepkg -si --noconfirm
      args:
        chdir: /tmp/yay
      when: yay_check.failed

    - name: Clean up yay build directory
      file:
        path: /tmp/yay
        state: absent
      when: yay_check.failed

    - name: Install tools
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ packages.tools }}"

    - name: Install packages from AUR
      community.general.pacman:
        name: "{{ item }}"
        state: present
        executable: yay
        extra_args: --builddir /var/cache/yay
      loop: "{{ packages.yay }}"

    - name: Enable bluetoothd service
      become: true
      ansible.builtin.systemd:
        name: bluetooth
        enabled: true
        state: started

    - name: Enable Syncthing service for the user
      become: false
      ansible.builtin.systemd:
        name: syncthing
        enabled: true
        state: started
        scope: user
