---
- name: Setup Dotfiles
  hosts: localhost

  tasks:
    - name: Import Packages
      tags: packages
      include_vars:
        dir: ansible/variables
        files_matching: "packages.yaml"
        name: packages

    - name: Install core packages
      become: true
      tags: core
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages.main }}"

    - name: Run stow
      become: false
      tags: stow
      shell: "stow . --target {{ ansible_env.HOME }} --verbose=2"
      register: result
      changed_when: "'LINK:' in result.stderr"

    - name: Enable bluetoothd service
      become: true
      tags: services
      ansible.builtin.systemd:
        name: bluetooth
        enabled: true
        state: started

    - name: Enable Syncthing service for the user
      become: false
      tags: services
      ansible.builtin.systemd:
        name: syncthing
        enabled: true
        state: started
        scope: user
