---
- name: Setup Dotfiles
  hosts: localhost

  tasks:

    - name: Ensure the Arch Linux keyring is up to date
      ansible.builtin.pacman:
        name: archlinux-keyring
        state: latest

    - name: Import Packages
      include_vars:
        dir: ansible/variables
        files_matching: 'packages.yaml'
        name: packages

    - name: Install Ansible Galaxy Roles General
      become: false
      ansible.builtin.command: |
        ansible-galaxy collection install community.general

    - name: Install core packages
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ packages.main }}"

    - name: Run stow
      become: false
      shell: "stow . --target {{ ansible_env.HOME }} --verbose=2"
      register: result
      changed_when: "'LINK:' in result.stderr"

    - name: Install system fonts
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ packages.fonts }}"

    - name: Install tools
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop: "{{ packages.tools }}"

    - name: Enable bluetoothd service
      become: true
      ansible.builtin.systemd:
        name: bluetooth
        enabled: true
        state: started

    - name: Enable Syncthing service for the user
      become: false
      ansible.builtin.systemd:
        name: syncthing
        enabled: true
        state: started
        scope: user
