---
- name: Execute tasks for archbtw role
  block:

  rescue:
    - name: Handle errors
      ansible.builtin.debug:
        msg: "An error occurred in the main tasks block"
  always:
    - name: Cleanup
      ansible.builtin.debug:
        msg: "Main tasks block completed"
