---
- name: Execute tasks for archbtw role

  block:
    - name: Perform update
      become: true
      pacman:
        update_cache: true
        upgrade: true

    - name: Install packages with pacman
      become: true
      pacman:
        name: "{{ pacman_packages }}"
        state: present

    - name: Remove bloat from machine
      become: true
      pacman:
        name: "{{ bloat_list }}"
        state: absent

    - name: Make sure libvirtd is on
      become: true
      ansible.builtin.systemd:
        name: libvirtd.service
        enabled: true
        state: started

  rescue:
    - name: Handle errors
      ansible.builtin.debug:
        msg: "Wow something broke in Arch :/"

  always:
    - name: Cleanup
      ansible.builtin.debug:
        msg: "Main tasks block completed"
