- name: Running my arch BTW playbook
  hosts: local

  vars_files:
    - ./bloat_list.yaml
    - ./packages.yaml

  tasks:
    - name: Perform update
      become: true
      pacman:
        update_cache: true
        upgrade: true

    - name: Install packages with pacman
      become: true
      pacman:
        name: "{{ pacman_list }}"
        state: present

    - name: Remove bloat from machine
      become: true
      pacman:
        name: "{{ bloat_list }}"
        state: absent

  handlers:
    - name: Start and enable services
      become: true
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - libvirtd.service
        - polkit.service
        - docker.service
        - sddm.service

    - name: Add user to groups
      become: true
      user:
        name: amadeus
        groups: "{{ item }}"
        append: yes
      loop:
        - docker
        - libvirt
        - kvm
