pacman_list:
  - aalib
  - abseil-cpp
  - accounts-qml-module
  - accountsservice
  - acl
  - adobe-source-code-pro-fonts
  - adwaita-cursors
  - adwaita-icon-theme
  - aha
  - alsa-lib
  - alsa-plugins
  - alsa-topology-conf
  - alsa-ucm-conf
  - amd-ucode
  - ansible
  - ansible-core
  - aom
  - appstream
  - appstream-qt
  - archlinux-appstream-data
  - archlinux-keyring
  - argon2
  - ark
  - at-spi2-core
  - atkmm
  - attica
  - attr
  - audit
  - autoconf
  - automake
  - avahi
  - azure-cli
  - baloo
  - base
  - base-devel
  - bash
  - bat
  - binutils
  - bison
  - bluedevil
  - bluez
  - bluez-libs
  - bluez-qt
  - bolt
  - boost-libs
  - breeze
  - breeze-gtk
  - breeze-icons
  - bridge-utils
  - brotli
  - btop
  - btrfs-progs
  - bubblewrap
  - busybox
  - bzip2
  - c-ares
  - ca-certificates
  - ca-certificates-mozilla
  - ca-certificates-utils
  - cairo
  - cairomm
  - cantarell-fonts
  - capstone
  - cdparanoia
  - chrono-date
  - cifs-utils
  - clang
  - clinfo
  - cliphist
  - cmake
  - compiler-rt
  - confuse
  - containerd
  - convertlit
  - coreutils
  - cpio
  - cryptsetup
  - curl
  - dav1d
  - db
  - db5.3
  - dbus
  - dconf
  - ddcutil
  - debugedit
  - default-cursors
  - desktop-file-utils
  - device-mapper
  - diffutils
  - discord
  - discount
  - discover
  - dmidecode
  - dnsmasq
  - dnssec-anchors
  - docker
  - double-conversion
  - drkonqi
  - dtc
  - duktape
  - e2fsprogs
  - ebook-tools
  - editorconfig-core-c
  - edk2-ovmf
  - efibootmgr
  - efivar
  - egl-wayland
  - eglexternalplatform
  - ell
  - exiv2
  - expat
  - extra-cmake-modules
  - fakeroot
  - feh
  - ffmpeg
  - fftw
  - file
  - filesystem
  - findutils
  - flac
  - flashrom
  - flex
  - fmt
  - fontconfig
  - frameworkintegration
  - freeglut
  - freetype2
  - frei0r-plugins
  - fribidi
  - fuse-common
  - fuse3
  - fwupd
  - fwupd-efi
  - gawk
  - gc
  - gcab
  - gcc
  - gcc-libs
  - gcr
  - gcr-4
  - gdb
  - gdb-common
  - gdbm
  - gdk-pixbuf2
  - geoclue
  - gettext
  - giflib
  - git
  - glib-networking
  - glib2
  - glibc
  - glibmm
  - glslang
  - glu
  - gmp
  - gnome-autoar
  - gnome-desktop-4
  - gnome-desktop-common
  - gnu-free-fonts
  - gnupg
  - gnutls
  - go
  - gobject-introspection-runtime
  - gperftools
  - gpgme
  - gpm
  - gptfdisk
  - graphene
  - graphite
  - grep
  - grim
  - groff
  - gsettings-desktop-schemas
  - gsm
  - gssdp
  - gst-plugins-bad-libs
  - gst-plugins-base
  - gst-plugins-base-libs
  - gst-plugins-good
  - gstreamer
  - gtk-layer-shell
  - gtk-update-icon-cache
  - gtk-vnc
  - gtk2
  - gtk3
  - gtk4
  - gtkmm3
  - gtksourceview4
  - guile
  - gupnp
  - gupnp-igd
  - gvfs
  - gzip
  - harfbuzz
  - helm
  - hicolor-icon-theme
  - hidapi
  - highway
  - htop
  - http-parser
  - hwdata
  - hwloc
  - hyprland
  - i2c-tools
  - iana-etc
  - icu
  - imath
  - imlib2
  - iniparser
  - intel-gmmlib
  - intel-media-driver
  - iproute2
  - iptables
  - iputils
  - iso-codes
  - iwd
  - jack2
  - jansson
  - json-c
  - json-glib
  - jsoncpp
  - k9s
  - kaccounts-integration
  - kactivities
  - kactivities-stats
  - kactivitymanagerd
  - karchive
  - kate
  - kauth
  - kbd
  - kbookmarks
  - kcmutils
  - kcodecs
  - kcompletion
  - kconfig
  - kconfigwidgets
  - kcoreaddons
  - kcrash
  - kdbusaddons
  - kde-cli-tools
  - kde-gtk-config
  - kdeclarative
  - kdecoration
  - kded
  - kdelibs4support
  - kdenlive
  - kdeplasma-addons
  - kdesu
  - kdnssd
  - kdsoap
  - kdsoap-ws-discovery-client
  - kemoticons
  - keyutils
  - kfilemetadata
  - kgamma5
  - kglobalaccel
  - kguiaddons
  - kholidays
  - khotkeys
  - ki18n
  - kiconthemes
  - kidletime
  - kinfocenter
  - kio
  - kio-extras
  - kio-fuse
  - kirigami2
  - kitemmodels
  - kitemviews
  - kitty
  - kitty-shell-integration
  - kitty-terminfo
  - kjobwidgets
  - kmenuedit
  - kmod
  - knewstuff
  - knotifications
  - knotifyconfig
  - konsole
  - kpackage
  - kparts
  - kpeople
  - kpipewire
  - kpty
  - kquickcharts
  - krb5
  - krunner
  - kscreen
  - kscreenlocker
  - kservice
  - ksshaskpass
  - ksystemstats
  - ktexteditor
  - ktextwidgets
  - kubectl
  - kunitconversion
  - kuserfeedback
  - kwallet
  - kwallet-pam
  - kwayland
  - kwayland-integration
  - kwidgetsaddons
  - kwin
  - kwindowsystem
  - kwrited
  - kxmlgui
  - l-smash
  - lame
  - layer-shell-qt
  - lcms2
  - ldb
  - ldns
  - less
  - lib32-alsa-lib
  - lib32-alsa-plugins
  - lib32-amdvlk
  - lib32-brotli
  - lib32-bzip2
  - lib32-curl
  - lib32-e2fsprogs
  - lib32-expat
  - lib32-gcc-libs
  - lib32-glibc
  - lib32-icu
  - lib32-keyutils
  - lib32-krb5
  - lib32-libdrm
  - lib32-libelf
  - lib32-libffi
  - lib32-libglvnd
  - lib32-libgpg-error
  - lib32-libidn2
  - lib32-libldap
  - lib32-libpciaccess
  - lib32-libpsl
  - lib32-libssh2
  - lib32-libtasn1
  - lib32-libunistring
  - lib32-libunwind
  - lib32-libx11
  - lib32-libxau
  - lib32-libxcb
  - lib32-libxcrypt
  - lib32-libxdamage
  - lib32-libxdmcp
  - lib32-libxext
  - lib32-libxfixes
  - lib32-libxml2
  - lib32-libxshmfence
  - lib32-libxss
  - lib32-libxxf86vm
  - lib32-llvm-libs
  - lib32-lm_sensors
  - lib32-mesa
  - lib32-ncurses
  - lib32-nspr
  - lib32-nss
  - lib32-openssl
  - lib32-p11-kit
  - lib32-sqlite
  - lib32-vulkan-icd-loader
  - lib32-wayland
  - lib32-xz
  - lib32-zlib
  - lib32-zstd
  - libaccounts-glib
  - libaccounts-qt
  - libadwaita
  - libaio
  - libappindicator-gtk3
  - libarchive
  - libass
  - libassuan
  - libasyncns
  - libatasmart
  - libavc1394
  - libb2
  - libblockdev
  - libbluray
  - libbpf
  - libbs2b
  - libbsd
  - libburn
  - libbytesize
  - libcaca
  - libcacard
  - libcamera
  - libcamera-ipa
  - libcanberra
  - libcap
  - libcap-ng
  - libcbor
  - libcdio
  - libcdio-paranoia
  - libcloudproviders
  - libcolord
  - libcups
  - libdaemon
  - libdatrie
  - libdbusmenu-glib
  - libdbusmenu-gtk3
  - libdbusmenu-qt5
  - libdecor
  - libdisplay-info
  - libdmtx
  - libdrm
  - libdv
  - libdvdnav
  - libdvdread
  - libebur128
  - libedit
  - libelf
  - libepoxy
  - libevdev
  - libevent
  - libexif
  - libffi
  - libfontenc
  - libftdi
  - libgcrypt
  - libgexiv2
  - libgirepository
  - libgit2
  - libglvnd
  - libgpg-error
  - libgudev
  - libgusb
  - libical
  - libice
  - libidn2
  - libiec61883
  - libimobiledevice
  - libinih
  - libinput
  - libisl
  - libisoburn
  - libisofs
  - libjcat
  - libjpeg-turbo
  - libjxl
  - libkexiv2
  - libksba
  - libkscreen
  - libksysguard
  - libldap
  - libliftoff
  - libluv
  - libmbim
  - libmd
  - libmfx
  - libmm-glib
  - libmnl
  - libmodplug
  - libmpc
  - libmpdclient
  - libmtp
  - libnautilus-extension
  - libndp
  - libnetfilter_conntrack
  - libnewt
  - libnfnetlink
  - libnfs
  - libnftnl
  - libnghttp2
  - libnice
  - libnl
  - libnm
  - libnma
  - libnma-common
  - libnotify
  - libnsl
  - libogg
  - libomxil-bellagio
  - libopenmpt
  - libosinfo
  - libp11-kit
  - libpcap
  - libpciaccess
  - libpgm
  - libpipewire
  - libplacebo
  - libplist
  - libpng
  - libportal
  - libportal-gtk4
  - libproxy
  - libpsl
  - libpulse
  - libqaccessibilityclient
  - libqalculate
  - libqmi
  - libqrtr-glib
  - libraw1394
  - librsvg
  - librsync
  - libsamplerate
  - libsasl
  - libseccomp
  - libsecret
  - libshout
  - libsigc++
  - libslirp
  - libsm
  - libsmbios
  - libsndfile
  - libsodium
  - libsoup3
  - libsoxr
  - libssh
  - libssh2
  - libstemmer
  - libsysprof-capture
  - libtasn1
  - libteam
  - libtermkey
  - libthai
  - libtheora
  - libtiff
  - libtirpc
  - libtommath
  - libtool
  - libtraceevent
  - libtracefs
  - libunistring
  - libunwind
  - liburcu
  - liburing
  - libusb
  - libusbmuxd
  - libutempter
  - libuv
  - libva
  - libva-intel-driver
  - libva-mesa-driver
  - libvdpau
  - libverto
  - libvirt
  - libvirt-glib
  - libvirt-python
  - libvorbis
  - libvpx
  - libvterm
  - libwacom
  - libwbclient
  - libwebp
  - libwireplumber
  - libx11
  - libxau
  - libxaw
  - libxcb
  - libxcomposite
  - libxcrypt
  - libxcursor
  - libxcvt
  - libxdamage
  - libxdg-basedir
  - libxdmcp
  - libxext
  - libxfixes
  - libxfont2
  - libxft
  - libxi
  - libxinerama
  - libxkbcommon
  - libxkbcommon-x11
  - libxkbfile
  - libxml2
  - libxmlb
  - libxmu
  - libxpm
  - libxpresent
  - libxrandr
  - libxrender
  - libxres
  - libxshmfence
  - libxslt
  - libxss
  - libxt
  - libxtst
  - libxv
  - libxxf86vm
  - libyaml
  - libzip
  - licenses
  - linux
  - linux-api-headers
  - linux-firmware
  - linux-firmware-whence
  - llvm-libs
  - lm_sensors
  - lmdb
  - lsb-release
  - lsof
  - luajit
  - lxappearance
  - lz4
  - lzo
  - m4
  - make
  - mbedtls
  - md4c
  - mdadm
  - media-player-info
  - mesa
  - mesa-utils
  - milou
  - minikube
  - minizip
  - mkinitcpio
  - mkinitcpio-busybox
  - mlt
  - mobile-broadband-provider-info
  - modemmanager
  - modemmanager-qt
  - mpfr
  - mpg123
  - mpv
  - msgpack-c
  - mtdev
  - mujs
  - multipath-tools
  - nano
  - nautilus
  - ncurses
  - ndctl
  - neovim
  - nettle
  - network-manager-applet
  - networkmanager
  - networkmanager-qt
  - nftables
  - ninja
  - nm-connection-editor
  - node-gyp
  - nodejs
  - nodejs-nopt
  - noto-fonts
  - npm
  - npth
  - nspr
  - nss
  - numactl
  - obs-studio
  - ocl-icd
  - oniguruma
  - openal
  - opencore-amr
  - openexr
  - openjpeg2
  - openmpi
  - openpmix
  - openssh
  - openssl
  - opus
  - orc
  - osinfo-db
  - oxygen
  - oxygen-sounds
  - p11-kit
  - pacman
  - pacman-mirrorlist
  - pam
  - pambase
  - pango
  - pangomm
  - parted
  - patch
  - pavucontrol
  - pciutils
  - pcre
  - pcre2
  - pcsclite
  - perl
  - perl-error
  - perl-mailtools
  - perl-timedate
  - pfetch
  - phodav
  - phonon-qt5
  - phonon-qt5-gstreamer
  - pinentry
  - pipewire
  - pipewire-media-session
  - pixman
  - pkgconf
  - plasma-browser-integration
  - plasma-desktop
  - plasma-disks
  - plasma-firewall
  - plasma-framework
  - plasma-integration
  - plasma-meta
  - plasma-nm
  - plasma-pa
  - plasma-systemmonitor
  - plasma-thunderbolt
  - plasma-vault
  - plasma-wayland-session
  - plasma-welcome
  - plasma-workspace
  - plasma-workspace-wallpapers
  - playerctl
  - polkit
  - polkit-kde-agent
  - polkit-qt5
  - poppler
  - poppler-qt5
  - popt
  - portaudio
  - powerdevil
  - ppp
  - prison
  - procps-ng
  - protobuf
  - protobuf-c
  - psmisc
  - pulseaudio
  - purpose
  - python
  - python-attrs
  - python-bcrypt
  - python-cairo
  - python-cffi
  - python-chardet
  - python-cryptography
  - python-distro
  - python-gobject
  - python-idna
  - python-jinja
  - python-markupsafe
  - python-packaging
  - python-paramiko
  - python-pip
  - python-ply
  - python-psutil
  - python-pycparser
  - python-pynacl
  - python-requests
  - python-resolvelib
  - python-six
  - python-typing_extensions
  - python-urllib3
  - python-wheel
  - python-yaml
  - qca-qt5
  - qemu-audio-spice
  - qemu-base
  - qemu-block-curl
  - qemu-block-dmg
  - qemu-block-nfs
  - qemu-block-ssh
  - qemu-chardev-spice
  - qemu-common
  - qemu-hw-display-qxl
  - qemu-hw-display-virtio-gpu
  - qemu-hw-display-virtio-gpu-gl
  - qemu-hw-display-virtio-gpu-pci
  - qemu-hw-display-virtio-gpu-pci-gl
  - qemu-hw-display-virtio-vga
  - qemu-hw-display-virtio-vga-gl
  - qemu-hw-s390x-virtio-gpu-ccw
  - qemu-hw-usb-host
  - qemu-hw-usb-redirect
  - qemu-hw-usb-smartcard
  - qemu-img
  - qemu-pr-helper
  - qemu-system-x86
  - qemu-system-x86-firmware
  - qemu-tools
  - qemu-ui-curses
  - qemu-ui-opengl
  - qemu-ui-spice-app
  - qemu-ui-spice-core
  - qqc2-desktop-style
  - qrencode
  - qt5-base
  - qt5-declarative
  - qt5-graphicaleffects
  - qt5-location
  - qt5-multimedia
  - qt5-networkauth
  - qt5-quickcontrols
  - qt5-quickcontrols2
  - qt5-sensors
  - qt5-speech
  - qt5-svg
  - qt5-tools
  - qt5-translations
  - qt5-wayland
  - qt5-webchannel
  - qt5-webengine
  - qt5-webview
  - qt5-x11extras
  - qt6-base
  - qt6-svg
  - qt6-translations
  - rav1e
  - re2
  - readline
  - rhash
  - ripgrep
  - rnnoise
  - rofi
  - rtkit
  - rubberband
  - runc
  - sddm
  - sddm-kcm
  - sdl2
  - seabios
  - seatd
  - sed
  - semver
  - shaderc
  - shadow
  - shared-mime-info
  - signon-kwallet-extension
  - signon-plugin-oauth2
  - signon-ui
  - signond
  - slang
  - slurp
  - smartmontools
  - smbclient
  - snappy
  - sndio
  - socat
  - solid
  - sonnet
  - sound-theme-freedesktop
  - source-highlight
  - spdlog
  - spectacle
  - speex
  - speexdsp
  - spice
  - spice-gtk
  - spice-protocol
  - spirv-tools
  - sqlite
  - srt
  - startup-notification
  - steam
  - stow
  - sudo
  - svt-av1
  - swaybg
  - swaylock
  - syndication
  - syntax-highlighting
  - systemd
  - systemd-libs
  - systemd-sysvcompat
  - systemsettings
  - taglib
  - talloc
  - tar
  - tdb
  - tevent
  - texinfo
  - threadweaver
  - tor
  - tpm2-tss
  - tracker3
  - tree
  - tree-sitter
  - tslib
  - ttf-hack
  - twolame
  - tzdata
  - uchardet
  - udisks2
  - unibilium
  - unzip
  - upower
  - usbmuxd
  - usbredir
  - usbutils
  - util-linux
  - util-linux-libs
  - v4l-utils
  - vde2
  - vid.stab
  - vim
  - vim-runtime
  - virglrenderer
  - virt-install
  - virt-manager
  - virtiofsd
  - vivaldi
  - vmaf
  - volume_key
  - vte-common
  - vte3
  - vulkan-headers
  - vulkan-icd-loader
  - vulkan-intel
  - vulkan-radeon
  - vulkan-tools
  - vulkan-validation-layers
  - wavpack
  - waybar
  - wayland
  - wayland-protocols
  - wayland-utils
  - webrtc-audio-processing
  - wget
  - which
  - wireless_tools
  - wl-clipboard
  - wolfssl
  - wpa_supplicant
  - x264
  - x265
  - xcb-proto
  - xcb-util
  - xcb-util-cursor
  - xcb-util-errors
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xcb-util-xrm
  - xdg-desktop-portal
  - xdg-desktop-portal-kde
  - xdg-user-dirs
  - xdg-utils
  - xf86-input-libinput
  - xf86-video-amdgpu
  - xf86-video-ati
  - xf86-video-nouveau
  - xf86-video-vmware
  - xkeyboard-config
  - xorg-fonts-encodings
  - xorg-server
  - xorg-server-common
  - xorg-setxkbmap
  - xorg-xauth
  - xorg-xdpyinfo
  - xorg-xinit
  - xorg-xinput
  - xorg-xkbcomp
  - xorg-xmessage
  - xorg-xmodmap
  - xorg-xprop
  - xorg-xrandr
  - xorg-xrdb
  - xorg-xset
  - xorg-xsetroot
  - xorg-xwayland
  - xorgproto
  - xvidcore
  - xwaylandvideobridge-cursor-mode-2-git
  - xz
  - yajl
  - yay-git
  - zellij
  - zenity
  - zeromq
  - zimg
  - zlib
  - zram-generator
  - zsh
  - zstd
  - zxing-cpp
